<div class="wrap">
  <h2><img name="rot13_encoder_decoder_icon32" src="<?php echo WP_PLUGIN_URL . ROT13_ENCODER_DECODER_PLUGIN_DIR . "/img/rot13button32.png"; ?>" align="absmiddle" width="32" height="32" alt="" /> ROT13 Encoder/Decoder Settings</h2>
  <form action="options.php" method="post">
    <?php settings_fields('rot13_encoder_decoder'); ?>
    <?php do_settings_sections('rot13_encoder_decoder'); ?>
    <input class="button-primary" name="Submit" id="Submit" type="submit" value="<?php esc_attr_e('Save Changes'); ?>" />
  </form>
  	<h3>Contributions</h3>
	<p>If you have found this plugin helpful, feel free to send me a beer (well, its cash equivalent anyway... *L*) to help contribute to plugin support/future development/my sanity. Provide the website you're using the plugin on when you make payment, and I'll list it here in future releases.</p>
	<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
		<input type="hidden" name="cmd" value="_s-xclick">
		<input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHTwYJKoZIhvcNAQcEoIIHQDCCBzwCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYCQqMqnT9Lt7u+OaTbR3KnkLaUX7Yin4UcICAZWRu+gWFixOeu6Ctb6V4/uForMcKCDrNciuJgnyCtvXnXvNHjI5bZ/6j1Ui0WW3V5TKXcMolGuY3ff/cpGrmC+9wKji+TewltACJsYcBs7HxogdV23eHuzpek2C6XY7YsAZR7/mDELMAkGBSsOAwIaBQAwgcwGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIkWkFzhhKS7WAgaiNcxIZ/+d5iQMAWgxJvEFlVZjkC6Pnv+WDkPN+16zHt9yXTRZVWKwIDTAc1F7QP8KhalDZVaogAxwn6/44cu/WJquajxbLUNQfUxGIJoOJRNWs/Dpm47uSmlV6QnxlNtCIrAj7UNeRM32lPqbukMHNE2Yf2itZELm4lAdek5yQb5HZjktP/Q1gy7mqQRBq7yDd7A/ml3r8ikHaA8wdcllr7hursn44sYygggOHMIIDgzCCAuygAwIBAgIBADANBgkqhkiG9w0BAQUFADCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wHhcNMDQwMjEzMTAxMzE1WhcNMzUwMjEzMTAxMzE1WjCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMFHTt38RMxLXJyO2SmS+Ndl72T7oKJ4u4uw+6awntALWh03PewmIJuzbALScsTS4sZoS1fKciBGoh11gIfHzylvkdNe/hJl66/RGqrj5rFb08sAABNTzDTiqqNpJeBsYs/c2aiGozptX2RlnBktH+SUNpAajW724Nv2Wvhif6sFAgMBAAGjge4wgeswHQYDVR0OBBYEFJaffLvGbxe9WT9S1wob7BDWZJRrMIG7BgNVHSMEgbMwgbCAFJaffLvGbxe9WT9S1wob7BDWZJRroYGUpIGRMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbYIBADAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAIFfOlaagFrl71+jq6OKidbWFSE+Q4FqROvdgIONth+8kSK//Y/4ihuE4Ymvzn5ceE3S/iBSQQMjyvb+s2TWbQYDwcp129OPIbD9epdr4tJOUNiSojw7BHwYRiPh58S1xGlFgHFXwrEBb3dgNbMUa+u4qectsMAXpVHnD9wIyfmHMYIBmjCCAZYCAQEwgZQwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tAgEAMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xMTAzMTQyMTAwMDFaMCMGCSqGSIb3DQEJBDEWBBQXo4kRCwZTOekMW/iCQHvOz3/gBzANBgkqhkiG9w0BAQEFAASBgGvyqMJhMaDEz0/xvjFU+UMrbOaxZCXmieni+N1TyRTuHWgpJ8aDEjzYOvgnPzbLEKNsGg2fqn8VtevE/JnA4yN7WPB7iFGsl1OAIeD+ZR4R52C+0uFMU7AYwRqIkadepm+3m2Ro2wgesrxGTxSwEGfX2ccurTyhSmIP2LaphtOE-----END PKCS7-----
		">
		<input type="image" src="https://www.paypalobjects.com/WEBSCR-640-20110306-1/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
		<img alt="" border="0" src="https://www.paypalobjects.com/WEBSCR-640-20110306-1/en_US/i/scr/pixel.gif" width="1" height="1">
	</form>
</div>
